AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
Documentation:
  Enabled: false
LineLength:
  Max: 120
Style/RaiseArgs:
  EnforcedStyle: compact
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Lint/Debugger:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
